/*
 * FreeRTOS+TCP <DEVELOPMENT BRANCH>
 * Copyright (C) 2022 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * http://aws.amazon.com/freertos
 * http://www.FreeRTOS.org
 */

/**
 * @file IPTraceMacroDefaults.h
 * @brief This file provides default (empty) implementations for any IP trace
 *        macros that are not defined by the user.  See
 *        http://www.FreeRTOS.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/TCP_IP_Trace.html
 */

#ifndef IP_TRACE_MACRO_DEFAULTS_H
#define IP_TRACE_MACRO_DEFAULTS_H

#ifndef FREERTOS_IP_CONFIG_DEFAULTS_H
    #error FreeRTOSIPConfigDefaults.h has not been included yet
#endif

/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                       TCP/IP STACK TRACE MACROS                           */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceIP_EVENT_LOST
 *
 * Called when a packet generated by the TCP/IP stack is dropped because there
 * is insufficient space in the network event queue (see the
 * ipconfigEVENT_QUEUE_LENGTH setting in FreeRTOSIPConfig.h).
 */
#ifndef iptraceIP_EVENT_LOST
    #define iptraceIP_EVENT_LOST( eEvent )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceIP_EVENT_RECEIVED
 *
 * Called when the TCP/IP stack processes an event previously posted to the
 * network event queue. eEvent will be one of the following values:
 *
 * eNetworkDownEvent - The network interface has been lost and/or needs
 *                     [re]connecting.
 * eNetworkRxEvent - The network interface has queued a received Ethernet
 *                   frame.
 * eARPTimerEvent - The ARP timer expired.
 * eStackTxEvent - The software stack has queued a packet to transmit.
 * eDHCPEvent - Process the DHCP state machine.
 *
 * Note the events are defined by the private eIPEvent_t type which is not
 * generally accessible.
 */
#ifndef iptraceIP_EVENT_RECEIVED
    #define iptraceIP_EVENT_RECEIVED( eEvent )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceIP_NETWORK_DOWN
 *
 * Called when the network driver indicates that the network connection has
 * been lost (not implemented by all network drivers).
 */
#ifndef iptraceIP_NETWORK_DOWN
    #define iptraceIP_NETWORK_DOWN()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceIP_NETWORK_INPUT
 *
 * Called when a packet of length uxDataLength and with the contents at
 * address pucEthernetBuffer has been received.
 */
#ifndef iptraceIP_NETWORK_INPUT
    #define iptraceNETWORK_INPUT( uxDataLength, pucEthernetBuffer )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceIP_NETWORK_OUTPUT
 *
 * Called when a packet of length uxDataLength and with the contents at
 * address pucEthernetBuffer has been sent.
 */
#ifndef iptraceIP_NETWORK_OUTPUT
    #define iptraceNETWORK_OUTPUT( uxDataLength, pucEthernetBuffer )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceIP_TASK_STARTING
 *
 * A possibility to set some additional task properties.
 */
#ifndef iptraceIP_TASK_STARTING
    #define iptraceIP_TASK_STARTING()
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                            BUFFER TRACE MACROS                            */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceBUFFER_DESCRIPTOR_OBTAINED
 *
 * Called when the network buffer at address pxBufferAddress is obtained from
 * the TCP/IP stack by an RTOS task.
 */
#ifndef iptraceBUFFER_DESCRIPTOR_OBTAINED
    #define iptraceBUFFER_DESCRIPTOR_OBTAINED( pxBufferAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceBUFFER_DESCRIPTOR_OBTAINED_FROM_ISR
 *
 * Called when the network buffer at address pxBufferAddress is obtained from
 * the TCP/IP stack by an interrupt service routine.
 */
#ifndef iptraceBUFFER_DESCRIPTOR_OBTAINED_FROM_ISR
    #define iptraceBUFFER_DESCRIPTOR_OBTAINED_FROM_ISR( pxBufferAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceBUFFER_DESCRIPTOR_RELEASED
 *
 * Called when the network buffer at address pxBufferAddress is released back
 * to the TCP/IP stack.
 */
#ifndef iptraceBUFFER_DESCRIPTOR_RELEASED
    #define iptraceBUFFER_DESCRIPTOR_RELEASED( pxBufferAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceBUFFER_DESCRIPTOR_RELEASED_FROM_ISR
 *
 * Called when the network buffer at address pxBufferAddress is released back
 * to the TCP/IP stack by an interrupt service routine.
 */
#ifndef iptraceBUFFER_DESCRIPTOR_RELEASED_FROM_ISR
    #define iptraceBUFFER_DESCRIPTOR_RELEASED_FROM_ISR( pxBufferAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceBUFFER_FAILED_TO_OBTAIN_DESCRIPTOR
 *
 * Called when a task attempts to obtain a network buffer, but a buffer was
 * not available even after any defined block period.
 */
#ifndef iptraceBUFFER_FAILED_TO_OBTAIN_DESCRIPTOR
    #define iptraceBUFFER_FAILED_TO_OBTAIN_DESCRIPTOR()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceBUFFER_FAILED_TO_OBTAIN_DESCRIPTOR_FROM_ISR
 *
 * Called when an interrupt service routine attempts to obtain a network
 * buffer, but a buffer was not available.
 */
#ifndef iptraceBUFFER_FAILED_TO_OBTAIN_DESCRIPTOR_FROM_ISR
    #define iptraceBUFFER_FAILED_TO_OBTAIN_DESCRIPTOR_FROM_ISR()
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                           NETWORK TRACE MACROS                            */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                      NETWORK INTERFACE TRACE MACROS                       */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceNETWORK_INTERFACE_RECEIVE
 *
 * Called when a packet is received from the network by the network driver.
 * Note this macro is called by the network driver rather than the TCP/IP stack
 * and may not be called at all by drivers provided by third parties.
 */
#ifndef iptraceNETWORK_INTERFACE_RECEIVE
    #define iptraceNETWORK_INTERFACE_RECEIVE()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceNETWORK_INTERFACE_RX_EVENT_LOST
 *
 * Called when a packet received by the network driver is dropped for one of
 * the following reasons: There is insufficient space in the network event
 * queue (see the ipconfigEVENT_QUEUE_LENGTH setting in FreeRTOSIPConfig.h),
 * the received packet has an invalid data length, or there are no network
 * buffers available (see the ipconfigNUM_NETWORK_BUFFER_DESCRIPTORS setting
 * in FreeRTOSIPConfig.h). Note this macro is called by the network driver
 * rather than the TCP/IP stack and may not be called at all by drivers
 * provided by third parties.
 */
#ifndef iptraceNETWORK_INTERFACE_RX_EVENT_LOST
    #define iptraceNETWORK_INTERFACE_RX_EVENT_LOST()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceNETWORK_INTERFACE_TASK_STARTING
 *
 * Called when the network driver interface task has started.
 */
#ifndef iptraceNETWORK_INTERFACE_TASK_STARTING
    #define iptraceNETWORK_INTERFACE_TASK_STARTING()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceNETWORK_INTERFACE_TRANSMIT
 *
 * Called when a packet is sent to the network by the network driver. Note this
 * macro is called by the network driver rather than the TCP/IP stack and may
 * not be called at all by drivers provided by third parties.
 */
#ifndef iptraceNETWORK_INTERFACE_TRANSMIT
    #define iptraceNETWORK_INTERFACE_TRANSMIT()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceNETWORK_INTERFACE_WAITING_FOR_TX_DMA_DESCRIPTOR
 *
 * Called when a transmission at the network driver level cannot complete
 * immediately because the driver is having to wait for a DMA descriptor to
 * become free.
 */
#ifndef iptraceNETWORK_INTERFACE_WAITING_FOR_TX_DMA_DESCRIPTOR
    #define iptraceNETWORK_INTERFACE_WAITING_FOR_TX_DMA_DESCRIPTOR()
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                      NETWORK INTERFACE TRACE MACROS                       */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             IPv4 TRACE MACROS                             */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                             IPv4 TRACE MACROS                             */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             IPv6 TRACE MACROS                             */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                             IPv6 TRACE MACROS                             */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             TCP TRACE MACROS                              */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                             TCP TRACE MACROS                              */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             UDP TRACE MACROS                              */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceUDP_PACKET_DROPPED_TO_GENERATE_ARP
 *
 * Called when a packet destined for the IP address ulIPAddress is dropped
 * because the ARP cache does not contain an entry for the IP address. The
 * packet is automatically replaced by an ARP packet. ulIPAddress is expressed
 * as a 32-bit number in network byte order.
 */
#ifndef iptraceUDP_PACKET_DROPPED_TO_GENERATE_ARP
    #define iptraceUDP_PACKET_DROPPED_TO_GENERATE_ARP( ulIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceUDP_SENDING_PACKET
 *
 * Called when a UDP packet is sent to the IP address ulIPAddress. ulIPAddress
 * is expressed as a 32-bit number in network byte order.
 */
#ifndef iptraceUDP_SENDING_PACKET
    #define iptraceUDP_SENDING_PACKET( ulIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                             UDP TRACE MACROS                              */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                           SOCKET TRACE MACROS                             */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_BIND_FAILED
 *
 * A call to FreeRTOS_bind() failed. usPort is the port number the socket
 * xSocket was to be bound to.
 */
#ifndef iptraceSOCKET_BIND_FAILED
    #define iptraceSOCKET_BIND_FAILED( pxSocket, usPort )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_FAILED_TO_CREATE_SOCKET
 *
 * A call to FreeRTOS_socket() failed because there was insufficient FreeRTOS
 * heap memory available for the socket structure to be created.
 */
#ifndef iptraceSOCKET_FAILED_TO_CREATE_SOCKET
    #define iptraceSOCKET_FAILED_TO_CREATE_SOCKET()
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceSOCKET_FAILED_TO_CREATE_EVENT_GROUP
 *
 * Called when an event group could not be created, possibly due to
 * insufficient heap space, during new socket creation.
 */
#ifndef iptraceSOCKET_FAILED_TO_CREATE_EVENT_GROUP
    #define iptraceSOCKET_FAILED_TO_CREATE_EVENT_GROUP()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_NO_BUFFER_FOR_SENDTO
 *
 * Called when a call to FreeRTOS_sendto() tries to allocate a buffer, but a
 * buffer was not available even after any defined block period.
 */
#ifndef iptraceSOCKET_NO_BUFFER_FOR_SENDTO
    #define iptraceSOCKET_NO_BUFFER_FOR_SENDTO( pxSocket )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_RECVFROM_DISCARDING_BYTES
 *
 * FreeRTOS_recvfrom() is discarding xNumberOfBytesDiscarded bytes because the
 * number of bytes received is greater than the number of bytes that will fit
 * in the user supplied buffer (the buffer passed in as a FreeRTOS_recvfrom()
 * function parameter).
 */
#ifndef iptraceSOCKET_RECVFROM_DISCARDING_BYTES
    #define iptraceSOCKET_RECVFROM_DISCARDING_BYTES( xNumberOfBytesDiscarded )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_RECVFROM_INTERRUPTED
 *
 * Called when a blocking call to FreeRTOS_recvfrom() is interrupted through a
 * call to FreeRTOS_SignalSocket().
 */
#ifndef iptraceSOCKET_RECVFROM_INTERRUPTED
    #define iptraceSOCKET_RECVFROM_INTERRUPTED( pxSocket )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_RECVFROM_TIMEOUT
 *
 * Called when FreeRTOS_recvfrom() gets no data on the given socket even after
 * any defined block period.
 */
#ifndef iptraceSOCKET_RECVFROM_TIMEOUT
    #define iptraceSOCKET_RECVFROM_TIMEOUT( pxSocket )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_SENDTO_DATA_TOO_LONG
 *
 * Called when the data requested to be sent using a call to FreeRTOS_sendto()
 * is too long and could not be sent.
 */
#ifndef iptraceSOCKET_SENDTO_DATA_TOO_LONG
    #define iptraceSOCKET_SENDTO_DATA_TOO_LONG( pxSocket, overflow )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceSOCKET_SENDTO_NOT_BOUND
 *
 * Called when the socket used in the call to FreeRTOS_sendto() is not already
 * bound to a port.
 */
#ifndef iptraceSOCKET_SENDTO_NOT_BOUND
    #define iptraceSOCKET_SENDTO_NOT_BOUND( pxSocket )
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                           SOCKET TRACE MACROS                             */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             ARP TRACE MACROS                              */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_CREATING_REQUEST
 *
 * Called when the IP generates an ARP request packet.
 */
#ifndef iptraceARP_CREATING_REQUEST
    #define iptraceARP_CREATING_REQUEST( ulIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_DELAYED_BUFFER_FULL
 *
 * A packet has come in from an unknown IPv4 address. An ARP request has been
 * sent, but the queue is still filled with a different packet.
 */
#ifndef iptraceARP_DELAYED_BUFFER_FULL
    #define iptraceARP_DELAYED_BUFFER_FULL()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptrace_ARP_DELAYED_REQUEST_REPLIED
 *
 * An ARP request has been sent, and a matching reply is received. Now the
 * original packet will be processed by the IP-task.
 */
#ifndef iptrace_ARP_DELAYED_REQUEST_REPLIED
    #define iptrace_ARP_DELAYED_REQUEST_REPLIED()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_DELAYED_REQUEST_STARTED
 *
 * A packet came in from an unknown IPv4 address. An ARP request has been sent
 * and the network buffer is stored for processing later.
 */
#ifndef iptraceARP_DELAYED_REQUEST_STARTED
    #define iptraceARP_DELAYED_REQUEST_STARTED()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_DELAYED_TIMER_EXPIRED
 *
 * A packet was stored for delayed processing, but there is no ARP reply. The
 * network buffer will be released without being processed.
 */
#ifndef iptraceARP_DELAYED_TIMER_EXPIRED
    #define iptraceARP_DELAYED_TIMER_EXPIRED()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_DROPPED_INVALID_PACKET
 *
 * Called when an ARP packet is dropped due to invalid protocol and hardware
 * fields in the header at address pxARPHeader.
 */
#ifndef iptraceARP_DROPPED_INVALID_PACKET
    #define iptraceDROPPED_INVALID_ARP_PACKET( pxARPHeader )
#endif

/*---------------------------------------------------------------------------*/

/*
 * traceARP_PACKET_RECEIVED
 *
 * Called when an ARP packet is received, even if the local network node is not
 * involved in the ARP transaction.
 */
#ifndef traceARP_PACKET_RECEIVED
    #define traceARP_PACKET_RECEIVED()
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_PROCESSING_RECEIVED_REPLY
 *
 * Called when the ARP cache is about to be updated in response to the
 * reception of an ARP reply. ulIPAddress holds the ARP message's target IP
 * address (as a 32-bit number in network byte order), which may not be the
 * local network node (depending on the FreeRTOSIPConfig.h settings).
 */
#ifndef iptraceARP_PROCESSING_RECEIVED_REPLY
    #define iptraceARP_PROCESSING_RECEIVED_REPLY( ulIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_SENDING_REPLY
 *
 * An ARP reply is being sent in response to an ARP request from the IP address
 * ulIPAddress. ulIPAddress is expressed as a 32-bit number in network byte
 * order.
 */
#ifndef iptraceARP_SENDING_REPLY
    #define iptraceARP_SENDING_REPLY( ulIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_TABLE_ENTRY_CREATED
 *
 * Called when a new entry in the ARP table is created to map the IP address
 * ulIPAddress to the MAC address ucMACAddress. ulIPAddress is expressed as a
 * 32-bit number in network byte order. ucMACAddress is a pointer to an
 * MACAddress_t structure.
 */
#ifndef iptraceARP_TABLE_ENTRY_CREATED
    #define iptraceARP_TABLE_ENTRY_CREATED( ulIPAddress, ucMACAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_TABLE_ENTRY_EXPIRED
 *
 * Called when the entry for the IP address ulIPAddress in the ARP cache is
 * removed. ulIPAddress is expressed as a 32-bit number in network byte order.
 */
#ifndef iptraceARP_TABLE_ENTRY_EXPIRED
    #define iptraceARP_TABLE_ENTRY_EXPIRED( ulIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceARP_TABLE_ENTRY_WILL_EXPIRE
 *
 * Called when an ARP request is about to be sent because the entry for the IP
 * address ulIPAddress in the ARP cache has become stale. ulIPAddress is
 * expressed as a 32-bit number in network byte order.
 */
#ifndef iptraceARP_TABLE_ENTRY_WILL_EXPIRE
    #define iptraceARP_TABLE_ENTRY_WILL_EXPIRE( ulIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                             ARP TRACE MACROS                              */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             DHCP TRACE MACROS                             */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceDHCP_REQUESTS_FAILED_USING_DEFAULT_IP_ADDRESS
 *
 * Called when the default IP address is used because an IP address could not
 * be obtained from a DHCP. ulIPAddress is expressed as a 32-bit number in
 * network byte order.
 */
#ifndef iptraceDHCP_REQUESTS_FAILED_USING_DEFAULT_IP_ADDRESS
    #define iptraceDHCP_REQUESTS_FAILED_USING_DEFAULT_IP_ADDRESS( ulIPAddress )
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceDHCP_REQUESTS_FAILED_USING_DEFAULT_IPv6_ADDRESS
 */
#ifndef iptraceDHCP_REQUESTS_FAILED_USING_DEFAULT_IPv6_ADDRESS
    #define iptraceDHCP_REQUESTS_FAILED_USING_DEFAULT_IPv6_ADDRESS( xIPAddress )
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceDHCP_SENDING_REQUEST
 *
 * Called when a DHCP request packet is sent.
 */
#ifndef iptraceDHCP_SENDING_REQUEST
    #define iptraceSENDING_DHCP_REQUEST()
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceDHCP_SENDING_DISCOVER
 *
 * Called when a DHCP discover packet is sent.
 */
#ifndef iptraceDHCP_SENDING_DISCOVER
    #define iptraceDHCP_SENDING_DISCOVER()
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceDHCP_SUCCEEDED
 *
 * Called when DHCP negotiation is complete and the IP address in
 * ulOfferedIPAddress is offered to the device.
 */
#ifndef iptraceDHCP_SUCCEEDED
    #define iptraceDHCP_SUCCEEDED( ulOfferedIPAddress )
#endif

/*-----------------------------------------------------------------------*/

/*===========================================================================*/
/*                             DHCP TRACE MACROS                             */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             DNS TRACE MACROS                              */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceDNS_SENDING_REQUEST
 *
 * Called when a DNS request is sent.
 */
#ifndef iptraceDNS_SENDING_REQUEST
    #define iptraceDNS_SENDING_REQUEST()
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                             DNS TRACE MACROS                              */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             ICMP TRACE MACROS                             */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceICMP_PACKET_RECEIVED
 *
 * Called when an ICMP packet is received.
 */
#ifndef iptraceICMP_PACKET_RECEIVED
    #define iptraceICMP_PACKET_RECEIVED()
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceICMP_SENDING_REPLY
 *
 * Called when an ICMP echo reply (ping reply) is sent to the IP address
 * ulIPAddress in response to an ICMP echo request (ping request) originating
 * from the same address. ulIPAddress is expressed as a 32-bit number in
 * network byte order.
 */
#ifndef iptraceICMP_SENDING_REPLY
    #define iptraceICMP_SENDING_REPLY( ulIPAddress )
#endif

/*-----------------------------------------------------------------------*/

/*===========================================================================*/
/*                             ICMP TRACE MACROS                             */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             NDP TRACE MACROS                              */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceND_TABLE_ENTRY_EXPIRED
 */
#ifndef iptraceND_TABLE_ENTRY_EXPIRED
    #define iptraceND_TABLE_ENTRY_EXPIRED( pxIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceND_TABLE_ENTRY_WILL_EXPIRE
 */
#ifndef iptraceND_TABLE_ENTRY_WILL_EXPIRE
    #define iptraceND_TABLE_ENTRY_WILL_EXPIRE( pxIPAddress )
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                             NDP TRACE MACROS                              */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                      ROUTER ADVERTISEMENT TRACE MACROS                    */
/*===========================================================================*/

/*---------------------------------------------------------------------------*/

/*
 * iptraceRA_REQUESTS_FAILED_USING_DEFAULT_IP_ADDRESS
 */
#ifndef iptraceRA_REQUESTS_FAILED_USING_DEFAULT_IP_ADDRESS
    #define iptraceRA_REQUESTS_FAILED_USING_DEFAULT_IP_ADDRESS( ipv6_address )
#endif

/*---------------------------------------------------------------------------*/

/*
 * iptraceRA_SUCCEEDED
 */
#ifndef iptraceRA_SUCCEEDED
    #define iptraceRA_SUCCEEDED( ipv6_address )
#endif

/*---------------------------------------------------------------------------*/

/*===========================================================================*/
/*                      ROUTER ADVERTISEMENT TRACE MACROS                    */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                             MEM STATS MACROS                              */
/*===========================================================================*/

/*-----------------------------------------------------------------------*/

/*
 * iptraceMEM_STATS_CLOSE
 *
 * Should be called by the application when the collection of memory
 * statistics should be stopped.
 */
#ifndef iptraceMEM_STATS_CLOSE
    #define iptraceMEM_STATS_CLOSE()
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceMEM_STATS_CREATE
 *
 * Called when an object at address pxObject of type xMemType and size
 * uxSize has been allocated from the heap.
 */
#ifndef iptraceMEM_STATS_CREATE
    #define iptraceMEM_STATS_CREATE( xMemType, pxObject, uxSize )
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceMEM_STATS_DELETE
 *
 * Called when an object at address pxObject has been deallocated and the
 * memory has been returned to the heap.
 */
#ifndef iptraceMEM_STATS_DELETE
    #define iptraceMEM_STATS_DELETE( pxObject )
#endif

/*-----------------------------------------------------------------------*/

/*===========================================================================*/
/*                             MEM STATS MACROS                              */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/
/*                           TCP DUMP TRACE MACROS                           */
/*===========================================================================*/

/*-----------------------------------------------------------------------*/

/*
 * iptraceDUMP_INIT
 */
#ifndef iptraceDUMP_INIT
    #define iptraceDUMP_INIT( pcFileName, pxEntries )
#endif

/*-----------------------------------------------------------------------*/

/*
 * iptraceDUMP_PACKET
 */
#ifndef iptraceDUMP_PACKET
    #define iptraceDUMP_PACKET( pucBuffer, uxLength, xIncoming )
#endif

/*-----------------------------------------------------------------------*/

/*===========================================================================*/
/*                           TCP DUMP TRACE MACROS                           */
/*===========================================================================*/
/*---------------------------------------------------------------------------*/
/*===========================================================================*/

#endif /* IP_TRACE_MACRO_DEFAULTS_H */
