#include "main.h"
#include "mpu.h"

void MPU_Config(void)
{
	LL_MPU_Disable();

	extern int __ETH_DESCRIPTORS_START, __ETH_BUFFERS_START;

	LL_MPU_ConfigRegion(
		LL_MPU_REGION_NUMBER0,
		0x0,
		( uint32_t )&__ETH_DESCRIPTORS_START,
		LL_MPU_REGION_SIZE_1KB|LL_MPU_TEX_LEVEL0|LL_MPU_REGION_FULL_ACCESS|\
		LL_MPU_INSTRUCTION_ACCESS_DISABLE|LL_MPU_ACCESS_NOT_SHAREABLE|LL_MPU_ACCESS_NOT_CACHEABLE|\
		LL_MPU_ACCESS_BUFFERABLE
	);
	LL_MPU_EnableRegion(LL_MPU_REGION_NUMBER0);

	LL_MPU_ConfigRegion(
		LL_MPU_REGION_NUMBER1,
		0x0,
		( uint32_t )&__ETH_BUFFERS_START,
		LL_MPU_REGION_SIZE_64KB|LL_MPU_TEX_LEVEL1|LL_MPU_REGION_FULL_ACCESS|\
		LL_MPU_INSTRUCTION_ACCESS_DISABLE|LL_MPU_ACCESS_NOT_SHAREABLE|LL_MPU_ACCESS_NOT_CACHEABLE|\
		LL_MPU_ACCESS_NOT_BUFFERABLE
	);
	LL_MPU_EnableRegion(LL_MPU_REGION_NUMBER1);

	LL_MPU_Enable(LL_MPU_CTRL_PRIVILEGED_DEFAULT);
}
